Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.name = "devops-bootcamp-linux-vm-task"
    v.memory = 2048
    v.cpus = 1
  end

  # require VAGRANT_EXPERIMENTAL="disks"
  config.vm.disk :disk, size: "1GB", name: "vm-task-lvm"
end
